Repository mung-manager/guest-be, pull requests merged in 2024-07, with the labels that each got.

#26 Feat #25 - 유치원 요약 정보 조회 API 구현
  mung_manager/pet_kindergardens/apis/api_managers.py
  mung_manager/pet_kindergardens/apis/apis.py
  mung_manager/pet_kindergardens/apis/urls.py
  mung_manager/pet_kindergardens/selectors/abstracts.py
  mung_manager/pet_kindergardens/selectors/pet_kindergardens.py
  mung_manager/pet_kindergardens/types.py
Labels: ✨ Feature

#28 Feat #27 - 커스텀 미들웨어 반려동물유치원 객체 주입 추가
  config/django/base.py
  config/settings/middleware.py
  mung_manager/apis/mixins.py
  mung_manager/apis/permissions.py
  mung_manager/pet_kindergardens/apis/api_managers.py
  mung_manager/pet_kindergardens/apis/apis.py
  mung_manager/pet_kindergardens/selectors/abstracts.py
  mung_manager/pet_kindergardens/selectors/pet_kindergardens.py
  mung_manager/pet_kindergardens/types.py
  mung_manager/reservations/apis/api_managers.py
  mung_manager/reservations/apis/apis.py
Labels: 🔨 Refactor, ✨ Feature

#30 Fix #29 - `typing_extensions` 의존성 부재로 발생하는 에러
  poetry.lock
  pyproject.toml
Labels: 🐞 BugFix

#34 Feat #33 - 고객의 예약 목록 조회 API 구현
  mung_manager/customers/apis/api_managers.py
  mung_manager/customers/apis/apis.py
  mung_manager/customers/apis/urls.py
  mung_manager/customers/selectors/abstracts.py
  mung_manager/customers/selectors/customers.py
  mung_manager/reservations/enums.py
  mung_manager/reservations/selectors/abstracts.py
  mung_manager/reservations/selectors/reservations.py
  mung_manager/schemas/errors/customers.py
Labels: ✨ Feature

#41 Feat #40 - 고객의 티켓 구매 내역 조회 API 구현
  mung_manager/customers/apis/api_managers.py
  mung_manager/customers/apis/apis.py
  mung_manager/customers/apis/urls.py
  mung_manager/customers/selectors/abstracts.py
  mung_manager/customers/selectors/customer_tickets.py
  mung_manager/customers/types.py
  mung_manager/pet_kindergardens/selectors/abstracts.py
  mung_manager/pet_kindergardens/selectors/pet_kindergardens.py
  mung_manager/pet_kindergardens/types.py
Labels: ✨ Feature

#37 Feat #36 - 고객의 상세 예약 목록 조회 API 구현
  mung_manager/customers/apis/api_managers.py
  mung_manager/customers/apis/apis.py
  mung_manager/customers/apis/urls.py
  mung_manager/reservations/selectors/abstracts.py
  mung_manager/reservations/selectors/reservations.py
  mung_manager/reservations/types.py
  mung_manager/tickets/enums.py
Labels: ✨ Feature

#39 Feat #38 - 유치원 상세 조회 API 구현
  mung_manager/pet_kindergardens/apis/api_managers.py
  mung_manager/pet_kindergardens/apis/apis.py
  mung_manager/pet_kindergardens/apis/urls.py
  mung_manager/tickets/selectors/abstracts.py
  mung_manager/tickets/selectors/tickets.py
Labels: ✨ Feature

#45 Feat #43 - 티켓 만료 여부 조회 API 구현
  mung_manager/reservations/apis/api_managers.py
  mung_manager/reservations/apis/apis.py
  mung_manager/reservations/apis/urls.py
  mung_manager/reservations/selectors/abstracts.py
  mung_manager/reservations/selectors/reservations.py
  mung_manager/reservations/services/abstracts.py
  mung_manager/reservations/services/reservations.py
  mung_manager/reservations/types.py
Labels: ✨ Feature

#47 Docs #46 - 고객의 상세 예약 목록 조회 문서 수정
  mung_manager/customers/apis/api_managers.py
Labels: 📃 Docs

#50 Feat #49 - 선택한 티켓 타입의 상세 정보 조회 API 구현
  mung_manager/commons/constants.py
  mung_manager/commons/validators.py
  mung_manager/customers/selectors/abstracts.py
  mung_manager/customers/selectors/customer_tickets.py
  mung_manager/reservations/apis/api_managers.py
  mung_manager/reservations/apis/apis.py
  mung_manager/reservations/apis/urls.py
Labels: ✨ Feature

#54 Feat #23 - 예약 가능한 날짜 조회 API 구현
  mung_manager/customers/selectors/abstracts.py
  mung_manager/customers/selectors/customer_tickets.py
  mung_manager/pet_kindergardens/selectors/abstracts.py
  mung_manager/pet_kindergardens/selectors/pet_kindergardens.py
  mung_manager/reservations/apis/api_managers.py
  mung_manager/reservations/apis/apis.py
  mung_manager/reservations/apis/urls.py
  mung_manager/reservations/containers.py
  mung_manager/reservations/selectors/abstracts.py
  mung_manager/reservations/selectors/daily_reservations.py
  mung_manager/reservations/selectors/days_off.py
  mung_manager/reservations/services/abstracts.py
  mung_manager/reservations/services/reservations.py
  mung_manager/schemas/errors/tickets.py
Labels: ✨ Feature

#51 Refactor #48 - 티켓 목록 조회 기능을 티켓 타입 목록 조회로 수정
  mung_manager/customers/selectors/abstracts.py
  mung_manager/customers/selectors/customer_tickets.py
  mung_manager/reservations/apis/api_managers.py
  mung_manager/reservations/apis/apis.py
  mung_manager/reservations/apis/urls.py
Labels: 🔨 Refactor

#53 Feat #52 - 등원 시간 조회 API 구현
  mung_manager/reservations/apis/api_managers.py
  mung_manager/reservations/apis/apis.py
  mung_manager/reservations/apis/urls.py
  mung_manager/reservations/services/abstracts.py
  mung_manager/reservations/services/reservations.py
Labels: ✨ Feature

#63 Fix #62 - 예약하기 API의 Swagger 설정 문제 해결
  mung_manager/customers/apis/api_managers.py
Labels: 🐞 BugFix
